experiments_name: "basic_bsr"

model:
  target: models.Unet
  params:
    in_channels: 6
    out_channels: 3
    block_out_channels: [64, 128, 128]
  resume: Null

train_dataset:
  target: datasets.LaionHRDataset
  params:
    data_root: "C:/MyDataset/BSR/laion-high-resolution/00000/"
    crop_size: 256

val_dataset:
  target: datasets.ValDataset
  params:
    data_root: "C:/Users/WJQpe/Desktop/research_rep/Real-SRFlow/datasets/val_image/"
    up_scale: 2
    num_image: 4

dataloader_train:
  num_workers: 2
  shuffle: True
  persistent_workers: True

batch_size: 2
seed: 3407
device: "cuda"
epochs: 50
log_step_freq: 50
weight_save_per_epoch: 2

optim:
  lr: 5e-4
  weight_decay: 0.1
  max_lr: 1e-3





